// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH3MYy_L5DANnkjG069srM3di2U4-odcw',
    appId: '1:819732732318:android:3ac5e4a800c8ae22985e8f',
    messagingSenderId: '819732732318',
    projectId: 'dolapta-ne-var-app-60b2f',
    storageBucket: 'dolapta-ne-var-app-60b2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI9vzVoqKW_S_mqVD8mJzHOq30z98MZ0g',
    appId: '1:819732732318:ios:f2335c0c86f3660a985e8f',
    messagingSenderId: '819732732318',
    projectId: 'dolapta-ne-var-app-60b2f',
    storageBucket: 'dolapta-ne-var-app-60b2f.appspot.com',
    iosClientId: '819732732318-rbnnanp8lk6uh481itmsumvase1rng3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.dolaptanevarapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI9vzVoqKW_S_mqVD8mJzHOq30z98MZ0g',
    appId: '1:819732732318:ios:62df10e4f6d7c6cc985e8f',
    messagingSenderId: '819732732318',
    projectId: 'dolapta-ne-var-app-60b2f',
    storageBucket: 'dolapta-ne-var-app-60b2f.appspot.com',
    iosClientId: '819732732318-59o0f7g107c8curi1afg7m51c2phibqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.dolaptanevarapp.RunnerTests',
  );
}
